import type { Metadata } from "next";
import { Geist, Open_Sans } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/layout/Navbar";
import { CartProvider } from "@/context/CartContext";
import { AuthProvider } from "@/context/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-open-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${openSans.variable} h-full antialiased`}
    >

      <body className="min-h-full flex flex-col">
        <AuthProvider>
          <CartProvider>
            <Navbar />

            <main>
              {children}
            </main>
          </CartProvider></AuthProvider>
      </body>

    </html>
  );
}
